apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: controllercontroldaemonsets.contrail-operators.juniper.net
spec:
  group: contrail-operators.juniper.net
  names:
    kind: ControllerControlDaemonSet
    listKind: ControllerControlDaemonSetList
    plural: controllercontroldaemonsets
    singular: controllercontroldaemonset
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
