// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsDaemonSet) DeepCopyInto(out *AnalyticsDaemonSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsDaemonSet.
func (in *AnalyticsDaemonSet) DeepCopy() *AnalyticsDaemonSet {
	if in == nil {
		return nil
	}
	out := new(AnalyticsDaemonSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnalyticsDaemonSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsDaemonSetList) DeepCopyInto(out *AnalyticsDaemonSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnalyticsDaemonSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsDaemonSetList.
func (in *AnalyticsDaemonSetList) DeepCopy() *AnalyticsDaemonSetList {
	if in == nil {
		return nil
	}
	out := new(AnalyticsDaemonSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnalyticsDaemonSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsDaemonSetSpec) DeepCopyInto(out *AnalyticsDaemonSetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsDaemonSetSpec.
func (in *AnalyticsDaemonSetSpec) DeepCopy() *AnalyticsDaemonSetSpec {
	if in == nil {
		return nil
	}
	out := new(AnalyticsDaemonSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsDaemonSetStatus) DeepCopyInto(out *AnalyticsDaemonSetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsDaemonSetStatus.
func (in *AnalyticsDaemonSetStatus) DeepCopy() *AnalyticsDaemonSetStatus {
	if in == nil {
		return nil
	}
	out := new(AnalyticsDaemonSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsDbDaemonSet) DeepCopyInto(out *AnalyticsDbDaemonSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsDbDaemonSet.
func (in *AnalyticsDbDaemonSet) DeepCopy() *AnalyticsDbDaemonSet {
	if in == nil {
		return nil
	}
	out := new(AnalyticsDbDaemonSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnalyticsDbDaemonSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsDbDaemonSetList) DeepCopyInto(out *AnalyticsDbDaemonSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnalyticsDbDaemonSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsDbDaemonSetList.
func (in *AnalyticsDbDaemonSetList) DeepCopy() *AnalyticsDbDaemonSetList {
	if in == nil {
		return nil
	}
	out := new(AnalyticsDbDaemonSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnalyticsDbDaemonSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsDbDaemonSetSpec) DeepCopyInto(out *AnalyticsDbDaemonSetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsDbDaemonSetSpec.
func (in *AnalyticsDbDaemonSetSpec) DeepCopy() *AnalyticsDbDaemonSetSpec {
	if in == nil {
		return nil
	}
	out := new(AnalyticsDbDaemonSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsDbDaemonSetStatus) DeepCopyInto(out *AnalyticsDbDaemonSetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsDbDaemonSetStatus.
func (in *AnalyticsDbDaemonSetStatus) DeepCopy() *AnalyticsDbDaemonSetStatus {
	if in == nil {
		return nil
	}
	out := new(AnalyticsDbDaemonSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDbDaemonSet) DeepCopyInto(out *ConfigDbDaemonSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDbDaemonSet.
func (in *ConfigDbDaemonSet) DeepCopy() *ConfigDbDaemonSet {
	if in == nil {
		return nil
	}
	out := new(ConfigDbDaemonSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigDbDaemonSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDbDaemonSetList) DeepCopyInto(out *ConfigDbDaemonSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigDbDaemonSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDbDaemonSetList.
func (in *ConfigDbDaemonSetList) DeepCopy() *ConfigDbDaemonSetList {
	if in == nil {
		return nil
	}
	out := new(ConfigDbDaemonSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigDbDaemonSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDbDaemonSetSpec) DeepCopyInto(out *ConfigDbDaemonSetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDbDaemonSetSpec.
func (in *ConfigDbDaemonSetSpec) DeepCopy() *ConfigDbDaemonSetSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigDbDaemonSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDbDaemonSetStatus) DeepCopyInto(out *ConfigDbDaemonSetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDbDaemonSetStatus.
func (in *ConfigDbDaemonSetStatus) DeepCopy() *ConfigDbDaemonSetStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigDbDaemonSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigDaemonSet) DeepCopyInto(out *ControllerConfigDaemonSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigDaemonSet.
func (in *ControllerConfigDaemonSet) DeepCopy() *ControllerConfigDaemonSet {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigDaemonSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerConfigDaemonSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigDaemonSetList) DeepCopyInto(out *ControllerConfigDaemonSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControllerConfigDaemonSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigDaemonSetList.
func (in *ControllerConfigDaemonSetList) DeepCopy() *ControllerConfigDaemonSetList {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigDaemonSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerConfigDaemonSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigDaemonSetSpec) DeepCopyInto(out *ControllerConfigDaemonSetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigDaemonSetSpec.
func (in *ControllerConfigDaemonSetSpec) DeepCopy() *ControllerConfigDaemonSetSpec {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigDaemonSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfigDaemonSetStatus) DeepCopyInto(out *ControllerConfigDaemonSetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfigDaemonSetStatus.
func (in *ControllerConfigDaemonSetStatus) DeepCopy() *ControllerConfigDaemonSetStatus {
	if in == nil {
		return nil
	}
	out := new(ControllerConfigDaemonSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerControlDaemonSet) DeepCopyInto(out *ControllerControlDaemonSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerControlDaemonSet.
func (in *ControllerControlDaemonSet) DeepCopy() *ControllerControlDaemonSet {
	if in == nil {
		return nil
	}
	out := new(ControllerControlDaemonSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerControlDaemonSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerControlDaemonSetList) DeepCopyInto(out *ControllerControlDaemonSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControllerControlDaemonSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerControlDaemonSetList.
func (in *ControllerControlDaemonSetList) DeepCopy() *ControllerControlDaemonSetList {
	if in == nil {
		return nil
	}
	out := new(ControllerControlDaemonSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControllerControlDaemonSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerControlDaemonSetSpec) DeepCopyInto(out *ControllerControlDaemonSetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerControlDaemonSetSpec.
func (in *ControllerControlDaemonSetSpec) DeepCopy() *ControllerControlDaemonSetSpec {
	if in == nil {
		return nil
	}
	out := new(ControllerControlDaemonSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerControlDaemonSetStatus) DeepCopyInto(out *ControllerControlDaemonSetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerControlDaemonSetStatus.
func (in *ControllerControlDaemonSetStatus) DeepCopy() *ControllerControlDaemonSetStatus {
	if in == nil {
		return nil
	}
	out := new(ControllerControlDaemonSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrouterDaemonSet) DeepCopyInto(out *VrouterDaemonSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrouterDaemonSet.
func (in *VrouterDaemonSet) DeepCopy() *VrouterDaemonSet {
	if in == nil {
		return nil
	}
	out := new(VrouterDaemonSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VrouterDaemonSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrouterDaemonSetList) DeepCopyInto(out *VrouterDaemonSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VrouterDaemonSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrouterDaemonSetList.
func (in *VrouterDaemonSetList) DeepCopy() *VrouterDaemonSetList {
	if in == nil {
		return nil
	}
	out := new(VrouterDaemonSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VrouterDaemonSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrouterDaemonSetSpec) DeepCopyInto(out *VrouterDaemonSetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrouterDaemonSetSpec.
func (in *VrouterDaemonSetSpec) DeepCopy() *VrouterDaemonSetSpec {
	if in == nil {
		return nil
	}
	out := new(VrouterDaemonSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrouterDaemonSetStatus) DeepCopyInto(out *VrouterDaemonSetStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrouterDaemonSetStatus.
func (in *VrouterDaemonSetStatus) DeepCopy() *VrouterDaemonSetStatus {
	if in == nil {
		return nil
	}
	out := new(VrouterDaemonSetStatus)
	in.DeepCopyInto(out)
	return out
}
