apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vrouter-agent-operator
spec:
  selector:
    matchLabels:
      name: vrouter-agent-operator
  template:
    metadata:
      labels:
        name: vrouter-agent-operator
    spec:
      hostNetwork: true
      tolerations:
      - key: "node.kubernetes.io/not-ready"
        operator: Exists
      serviceAccountName: vrouter-agent-operator
      containers:
        - name: vrouter-agent-operator
          # Replace this with the built image name
          image: "pvijayaragav/vrouter-agent-operator-image"
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - vrouter-agent-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vrouter-agent-operator"
