apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: contrail-all-in-one-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - contrail-all-in-one-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - vrouter-component.juniper.net
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - config-db-component.juniper.net
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - controller-config-component.juniper.net
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - controller-control-component.juniper.net
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - analytics-db-component.juniper.net
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - analytics-component.juniper.net
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - contrail-operators.juniper.net
  resources:
  - '*'
  - configdbdaemonsets
  - controllerconfigdaemonsets
  - controllercontroldaemonsets
  - analyticsdbdaemonsets
  - analyticsdaemonsets
  verbs:
  - '*'
